name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Navega até a pasta do projeto (criada pelo script User Data)
            cd /home/ec2-user/app
            
            # Baixa as últimas alterações do repositório
            git pull origin main
            
            # Reconstrói a imagem e reinicia o container em background
            docker compose up -d --build
